public class homeWork {
    public static void main(String[] args) {
        var dog = 8.0;
        var cat = 3.6;
        var paper = 763789;
        System.out.println(dog);
        System.out.println(cat);
        System.out.println(paper);
        dog = dog + 4;
        cat = cat + 4;
        paper = paper + 4;
        System.out.println(dog);
        System.out.println(cat);
        System.out.println(paper);
        dog = dog - 3.5;
        cat = cat - 1.6;
        paper = paper -  7639;
        System.out.println(dog);
        System.out.println(cat);
        System.out.println(paper);
        var friend = 19;
        System.out.println(friend);
        friend = friend + 2;
        System.out.println(friend);
        friend = friend / 7;
        System.out.println(friend);
        var frog = 3.5;
        System.out.println(frog);
        frog = frog * 10;
        System.out.println(frog);
        frog = frog / 3.5;
        System.out.println(frog);
        frog = frog + 4;
        System.out.println(frog);
        var firstBoxerWeight =  78.2;
        var secondBoxerWeight =  82.7;
        var totalBoxerWeight = firstBoxerWeight + secondBoxerWeight;
        System.out.println("Общая масса бойцов = " + totalBoxerWeight + "кг");
        var firstDifferenceBoxerWeight = secondBoxerWeight - firstBoxerWeight;
        System.out.println("Разница массы бойцов = " + firstDifferenceBoxerWeight + "кг");
        var secondDifferenceBoxerWeight = secondBoxerWeight % firstBoxerWeight;
        System.out.println("Остаток от деления между двумя весами = "  + secondDifferenceBoxerWeight);
        var hourOfWork = 640;
        var employeeWorking = 8;
        var numberOfEmployees = hourOfWork / employeeWorking;
        System.out.println("Всего работников в компании " + numberOfEmployees + " человек");
        numberOfEmployees = numberOfEmployees + 94;
        hourOfWork = hourOfWork / numberOfEmployees;
        System.out.println("Если в компании работает " + numberOfEmployees + " человека, то всего " + hourOfWork + "часов работы может быть распределено между сотрудниками");
    }
}
